repos:
    - repo: https://github.com/timothycrosley/isort
      rev: 5.0.4
      hooks:
        - id: isort
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
        - id: black
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.3
      hooks:
        - id: flake8
          args:
          - "--max-line-length=100"
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v0.790"  # 2020.10.21
      hooks:
        - id: mypy
default_language_version:
    python: python3