site_name: xnat-tools
site_description: Documentation for the xnat-tools model
site_url: http://brown-bnc.github.io/xnat-tools
theme:
  name: material
  features:
    - instant
    - tabs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
          rendering:
            show_root_heading: false
            show_root_toc_entry: false
            heading_level: 3
      watch:
        - xnat_tools

markdown_extensions:
  - admonition
  - codehilite

nav:
  - Getting Started:
    - Overview: index.md
    - Installation: installation.md
  - Converting to BIDS:
    - User Interface: interface.md
    - Running locally: run_local.md
    - Running on Oscar: run_oscar.md
  - Development:
    - Setting up your environment: dev_setup.md
    - Code standards: code_standards.md 
#   - API Reference: