[tool.poetry]
name = "xnat-tools"
version = "0.1.0"
description = ""
authors = ["Isabel Restrepo <isabelrestre@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
heudiconv = "^0.5.4"
six = "^1.14"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
xnat-heudiconv = "xnat_tools.run_heudiconv:run"
xnat-dicom-export = "xnat_tools.dicom_export:run"
xnat2bids = "xnat_tools.xnat2bids:run"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
