[tool.poetry]
name = "xnat-tools"
version = "0.1.0"
description = ""
authors = ["Isabel Restrepo <isabelrestre@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
heudiconv = "^0.5.0"
six = "^1.14"
pydicom = "^1.4.1"
coloredlogs = "^14.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
python-dotenv = "^0.12.0"
black = {version = "^19.10b0", allow-prereleases = true}
flake8 = "^3.8.3"

[tool.poetry.scripts]
bids-postprocess ="xnat_tools.bids_postprocess:run"
xnat-heudiconv = "xnat_tools.run_heudiconv:run"
xnat-dicom-export = "xnat_tools.dicom_export:run"
xnat2bids = "xnat_tools.xnat2bids:run"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
