name: Build Documentation using MkDocs 
on: [push]
jobs: 
  build: 
    name: Build and Deploy Documentation 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Master 
        uses: actions/checkout@v2 
      - name: Set up Python 3.7 
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.7.5' 
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install .
          pip install mkdocs mkdocs-material mkdocstrings mkdocs-versioning
      - name: Set up 
        run: | 
          mkdir site
          export VERSION=dev
          echo "Making docs for version $VERSION"
          (envsubst '${VERSION}' < mkdocs-template.yml) > mkdocs.yml
      - name: Sync 
        run: |
          cat mkdocs.yml
          mkdocs-versioning sync
          rm -rf site/dev
      - name: Deploy
        run: |
          mkdocs build
          mkdocs-versioning deploy