name: dev-docs 
on:
  push:
    branches-ignore:
      - master
jobs: 
  build: 
    name: Build and Deploy Documentation 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Master 
        uses: actions/checkout@v2 
      - name: Set up Python 3.7 
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.7.5' 
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install .
          pip install mkdocs mkdocs-material mkdocstrings mkdocs-versioning mkdocs-markdownextradata-plugin
          pip install typer-cli
      - name: Set up mkdocs config
        run: | 
          export VERSION=dev
          echo "Making docs for version $VERSION"
          (envsubst '${VERSION}' < mkdocs-template.yml) > mkdocs.yml
      - name: Generate CLI docs and copy CHANGELOG   
        run: |
          typer xnat_tools/xnat2bids.py utils docs --name xnat2bids --output docs/xnat2bids.md
          typer xnat_tools/dicom_export.py utils docs --name xnat-dicom-export --output docs/dicom_export.md
          typer xnat_tools/run_heudiconv.py utils docs --name xnat-heudiconv --output docs/run_heudiconv.md
          typer xnat_tools/bids_postprocess.py utils docs --name bids-postprocess --output docs/bids_postprocess.md
      - name: Push to remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "docs: Update CLI docs"
          git push
      - name: Sync 
        run: |
          git pull
          mkdocs-versioning sync
          rm -rf ./site/dev/
          rm -rf ./site/.git/
      - name: Build
        run: mkdocs build
      - name: Deploy
        run: mkdocs-versioning -v deploy