name: dev-docs 
on:
  push:
    branches-ignore:
      - main
jobs: 
  build: 
    name: Build and Deploy Documentation 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Main 
        uses: actions/checkout@v2 
      - name: Check CLI files that changed
        uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            xnat2bids:
              - 'xnat_tools/xnat2bids.py'
            dicom_export:
              - 'xnat_tools/dicom_export.py'
            run_heudiconv:
              - 'xnat_tools/run_heudiconv.py'
            bids_postprocess:
              - 'xnat_tools/bids_postprocess.py'
      - name: Set up Python 3.7 
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version' # Read python version from a file .python-version
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install .
          pip install mkdocs mkdocs-material mkdocstrings mkdocs-versioning mkdocs-markdownextradata-plugin
          pip install typer-cli
      - name: Set up mkdocs config
        run: | 
          export VERSION=dev
          echo "Making docs for version $VERSION"
          (envsubst '${VERSION}' < mkdocs-template.yml) > mkdocs.yml
      - name: xnat2bids CLI docs  
        if: steps.filter.outputs.xnat2bids == 'true'
        run: |
          typer xnat_tools/xnat2bids.py utils docs --name xnat2bids --output docs/xnat2bids.md
          sed -i -e 's|\([0-9][0-9]\)-\([0-9][0-9]\)-\([0-9]\{4\}\)-\([0-9][0-9]\)-\([0-9][0-9]\)-\([0-9][0-9]\)|current date - MM-DD-YYYY-HH-MM-SS|' docs/xnat2bids.md
      - name: dicom_export CLI docs  
        if: steps.filter.outputs.dicom_export == 'true'
        run: |
          typer xnat_tools/dicom_export.py utils docs --name dicom_export --output docs/dicom_export.md
          sed -i -e 's|\([0-9][0-9]\)-\([0-9][0-9]\)-\([0-9]\{4\}\)-\([0-9][0-9]\)-\([0-9][0-9]\)-\([0-9][0-9]\)|current date - MM-DD-YYYY-HH-MM-SS|' docs/dicom_export.md
      - name: run_heudiconv CLI docs  
        if: steps.filter.outputs.run_heudiconv == 'true'
        run: |
          typer xnat_tools/run_heudiconv.py utils docs --name run_heudiconv --output docs/run_heudiconv.md
          sed -i -e 's|\([0-9][0-9]\)-\([0-9][0-9]\)-\([0-9]\{4\}\)-\([0-9][0-9]\)-\([0-9][0-9]\)-\([0-9][0-9]\)|current date - MM-DD-YYYY-HH-MM-SS|' docs/run_heudiconv.md
      - name: bids_postprocess CLI docs  
        if: steps.filter.outputs.bids_postprocess == 'true'
        run: |
          typer xnat_tools/bids_postprocess.py utils docs --name bids_postprocess --output docs/bids_postprocess.md
          sed -i -e 's|\([0-9][0-9]\)-\([0-9][0-9]\)-\([0-9]\{4\}\)-\([0-9][0-9]\)-\([0-9][0-9]\)-\([0-9][0-9]\)|current date - MM-DD-YYYY-HH-MM-SS|' docs/bids_postprocess.md
      - name: Push to remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git diff --quiet && git diff --staged --quiet || git commit -am "docs: Update CLI docs"
          git push
      - name: Sync 
        run: |
          git pull
          mkdocs-versioning sync
          rm -rf ./site/dev/
          rm -rf ./site/.git/
      - name: Build
        run: mkdocs build
      - name: Deploy
        run: mkdocs-versioning -v deploy