name: Docker Image CI

on:
  push:
  release:
    types: [published,created,edited,prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag xnat-tools:${GITHUB_SHA}
    - name: Publish the Docker image
      run: |
        docker login docker.pkg.github.com --username ${GITHUB_ACTOR} --password ${GITHUB_TOKEN}
        docker tag xnat-tools:${GITHUB_SHA} docker.pkg.github.com/brown-bnc/xnat-tools/xnat-tools:${GITHUB_REF:11}
        docker push docker.pkg.github.com/brown-bnc/xnat-tools/xnat-tools:${GITHUB_REF:11}
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
