name: New release and versioned docs 
on: 
  push:
    master
jobs: 
  release:
    name: Publish release
    runs-on: ubuntu-latest 
    steps:
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0    
        - name: Python Semantic Release
          uses: relekang/python-semantic-release@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
  docs:  
    name: Build and Deploy Documentation 
    runs-on: ubuntu-latest 
    depends-on: 
    steps: 
      - name: Checkout Master 
        uses: actions/checkout@v2 
      - name: Set up Python 3.7 
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.x' 
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install poetry
          poetry install 
      - name: Deploy 
        run: | 
          git pull
          mkdir site
          VERSION=$(cat pyproject.toml | grep version | head -1 | awk -F: '{ print $1 }'| sed 's/[\",]//g'| tr -d 'version = ')
          echo "Making docs for version $VERSION"
          (envsubst '${VERSION}' < mkdocs-template.yml) > mkdocs.yml
          poetry run mkdocs-versioning sync
          poetry run mkdocs build
          poetry run mkdocs-versioning deploy