name: New release and versioned docs 
on: 
  push:
    master
jobs: 
  bump_version:
    runs-on: ubuntu-latest
    name: 'Bump version and create changelog with commitizen'
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create bump and changelog
      uses: commitizen-tools/commitizen-action@0.3.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  docs:  
    name: Build and Deploy Documentation 
    runs-on: ubuntu-latest 
    depends-on: release
    steps: 
      - name: Checkout Master 
        uses: actions/checkout@v2 
      - name: Set up Python 3.7 
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.x' 
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install poetry
          poetry install 
      - name: Deploy 
        run: | 
          git pull
          mkdir site
          VERSION=$(cat pyproject.toml | grep version | head -1 | awk -F: '{ print $1 }'| sed 's/[\",]//g'| tr -d 'version = ')
          echo "Making docs for version $VERSION"
          (envsubst 'v${VERSION}' < mkdocs-template.yml) > mkdocs.yml
          poetry run mkdocs-versioning sync
          poetry run mkdocs build
          poetry run mkdocs-versioning deploy