name: tests 
on: 
  pull_request:
  push:
    branches: 
      - 'main'
env:
  XNAT_USER: '${{secrets.XNAT_USER}}'
  XNAT_PASS: '${{secrets.XNAT_PASS}}'
jobs: 
  test: 
    name: Run unit and integration tests 
    runs-on: self-hosted
    container:
      image: ghcr.io/brown-bnc/xnat-tools:latest
    steps: 
      - name: Test 
        run: pytest -x -s -o log_cli=true --log-cli-level=INFO tests/integration/test_xnat2bids.py