name: tests 
on: 
  pull_request:
  push:
    branches: 
      - 'main'
env:
  XNAT_USER: '${{secrets.XNAT_USER}}'
  XNAT_PASS: '${{secrets.XNAT_PASS}}'
jobs: 
  test: 
    name: Run unit and integration tests 
    runs-on: self-hosted
    container:
      image: ghcr.io/brown-bnc/xnat-tools:latest
    steps: 
      - name: Checkout Main 
        uses: actions/checkout@v2 
      - name: Set up Python 3.10 
        uses: actions/setup-python@v4 
        with:
          python-version-file: '.python-version' # Read python version from a file .python-version
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install .
          pip install pytest python-dotenv responses
          sudo apt update
          sudo apt-get update
          sudo apt-get -y install dcm2niix 
      - name: Test 
        run: pytest -x -s -o log_cli=true --log-cli-level=INFO 