name: tests 
on: 
  pull_request:
  push:
    branches: 
      - 'main'
env:
  XNAT_USER: '${{secrets.XNAT_USER}}'
  XNAT_PASS: '${{secrets.XNAT_PASS}}'
jobs: 
  test: 
    name: Run unit and integration tests 
    runs-on: self-hosted
    steps: 
      - name: Checkout Main 
        uses: actions/checkout@v2 
      - name: Set up Python 3.7 
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.7.5' 
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install .
          pip install pytest python-dotenv responses
          brew install dcm2niix
      - name: Test 
        run: pytest -x -s -o log_cli=true --log-cli-level=INFO 