name: tests 
on: [push]
jobs: 
  test: 
    name: Run unit tests 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Main 
        uses: actions/checkout@v2 
      - name: Set up Python 3.7 
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.7.5' 
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install .
          pip install pytest python-dotenv responses
      - name: Test 
        run: pytest -k unit